CREATE TABLE STATEMENT(
    STM# VARCHAR(9),
    STATMENTDATE CHAR (10),
    SALESPERSON# VARCHAR (20),
    CUST# NUMBER(3),
    CONSTRAINT STATMENT_STM#_FK PRIMARY KEY (STM#));

CREATE TABLE STATEMENT_EQUIPMENT(
    STM# VARCHAR(9),
    EQP# VARCHAR(9),
    QTY NUMBER(4),
    CHARGE NUMBER (6,2),
    CONSTRAINT STATMENT_EQUIPMENT_STM#_FK FOREIGN KEY(STM#)
    REFERENCES STATEMENT (STM#)
    );

CREATE TABLE EQUIP_TYPE(
    EQPTYPE# CHAR(3),
    EQPTYPEDESC CHAR(20),
    CONSTRAINT EQUIP_TYPE_EQPTYPE_FK PRIMARY KEY (EQPTYPE#));

CREATE TABLE CUSTOMER (
    Customer_Number NUMBER PRIMARY KEY,
    First_Name VARCHAR2(50),
    Last_Name VARCHAR2(50),
    Address VARCHAR2(100),
    Phone VARCHAR2(20),
    Federal_GST_LicenseNumber VARCHAR2(20)
);

CREATE TABLE SALESPERSON (
    Sales_Person_Num NUMBER PRIMARY KEY,
    Sales_Person_Name VARCHAR2(50)
);

CREATE TABLE EQUIPMENT (
    Eqp# VARCHAR(30) PRIMARY KEY,
    EqpDesc VARCHAR(100),
    EqpType# VARCHAR(30));
