ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUST#);

ALTER TABLE EQUIP_TYPE
ADD CONSTRAINT EQUIP_TYPE_PK PRIMARY KEY (EQP_TYPE#);

ALTER TABLE STATEMENT
ADD CONSTRAINT STATEMENT_PK PRIMARY KEY(STM#)
ADD CONSTRAINT STATEMENT_SALES_PERSON#_FK FOREIGN KEY (SALES_PERSON#)
    REFERENCES SALESPERSON(SALES_PERSON#)
ADD CONSTRAINT STATEMENT_CUST#_FK FOREIGN KEY (CUST#)
    REFERENCES CUSTOMER(CUST#);

ALTER TABLE EQUIPMENT
ADD CONSTRAINT EQUIPMENT_PK PRIMARY KEY(EQP#)
ADD CONSTRAINT EQUIPMENT_EQP_TYPE_FK FOREIGN KEY(EQP_TYPE#)
    REFERENCES EQUIP_TYPE(EQP_TYPE#);

ALTER TABLE SALESPERSON
ADD CONSTRAINT SALESPERSON_PK PRIMARY KEY(SALES_PERSON#)
ADD CONSTRAINT SALESPERSON_SALES_PERSON#_FK FOREIGN KEY(SALES_PERSON#)
    REFERENCES STATEMENT (SALES_PERSON#);

ALTER TABLE STATEMENT_EQUIPMENT
ADD CONSTRAINT STATMENT_EQUIPMENT_STM#_FK FOREIGN KEY(STM#)
    REFERENCES STATEMENT (STM#)
ADD CONSTRAINT STATMENT_EQUIPMENT_EQP#_FK FOREIGN KEY(EQP#)
    REFERENCES EQUIPMENT (EQP#);

COMMIT;
