SELECT * FROM STATEMENT;
SELECT * FROM STATEMENT_EQUIPMENT;
SELECT * FROM EQUIP_TYPE;
SELECT * FROM CUSTOMER;
SELECT * FROM SALESPERSON;
SELECT * FROM EQUIPMENT;

DROP TABLE STATEMENT;
DROP TABLE STATEMENT_EQUIPMENT;
DROP TABLE EQUIP_TYPE;
DROP TABLE CUSTOMER;
DROP TABLE SALESPERSON;
DROP TABLE EQUIPMENT;

CREATE TABLE STATEMENT(
    STM# VARCHAR(9),
    STATMENT_DATE CHAR (10),
    SALES_PERSON# VARCHAR (20),
    CUST# NUMBER(3),
    
    CONSTRAINT STATMENT_STM#_FK PRIMARY KEY (STM#),
    
    CONSTRAINT STATEMENT_SALES_PERSON#_FK FOREIGN KEY (SALES_PERSON#)
    REFERENCES SALESPERSON(SALES_PERSON#),
    
    CONSTRAINT STATEMENT_CUST#_FK FOREIGN KEY (CUST#)
    REFERENCES CUSTOMER(CUST#)); 

CREATE TABLE STATEMENT_EQUIPMENT(
    STM# VARCHAR(9),
    EQP# VARCHAR(9),
    QTY NUMBER(4),
    CHARGE NUMBER (6,2),
    
    CONSTRAINT STATMENT_EQUIPMENT_STM#_FK FOREIGN KEY(STM#)
    REFERENCES STATEMENT (STM#),
    
    CONSTRAINT STATMENT_EQUIPMENT_EQP#_FK FOREIGN KEY(EQP#)
    REFERENCES EQUIPMENT (EQP#));

CREATE TABLE EQUIP_TYPE(
    EQP_TYPE# CHAR(3),
    EQP_TYPE_DESC CHAR(20),
    CONSTRAINT EQUIP_TYPE_EQP_TYPE_PK PRIMARY KEY (EQP_TYPE#));

CREATE TABLE SALESPERSON (
    SALES_PERSON# VARCHAR (20) PRIMARY KEY,
    SALES_PERSON_NAME VARCHAR2(50)
);

CREATE TABLE EQUIPMENT (
    EQP# VARCHAR(30) PRIMARY KEY,
    EQPDESC VARCHAR(100),
    EQP_TYPE# CHAR(3),
    CONSTRAINT EQUIPMENT_EQP_TYPE#_FK FOREIGN KEY(EQP_TYPE#)
    REFERENCES EQUIP_TYPE (EQP_TYPE#));

CREATE TABLE CUSTOMER (
    CUST# NUMBER(3) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    ADDRESS VARCHAR2(100),
    PHONE VARCHAR2(20),
    FEDERAL_GST_LICENSENUMBER VARCHAR2(20)
);

INSERT INTO STATEMENT VALUES('EAP-44720','2024-11-17','29-Carey Wong',26 );
INSERT INTO STATEMENT_EQUIPMENT VALUES('EAP-44720','P100',250,4000);






