ALTER TABLE EQUIPMENT
DROP CONSTRAINT EQUIPMENT_EQP_TYPE_FK;

ALTER TABLE EQUIPMENT
ADD CONSTRAINT EQUIPMENT_EQP_TYPE#_FK 
FOREIGN KEY(EQP_TYPE#)
REFERENCES EQUIP_TYPE(EQP_TYPE#)
ON DELETE SET NULL;

ALTER TABLE STATEMENT_EQUIPMENT
DROP CONSTRAINT STATEMENT_EQUIPMENT_EQP#_FK;

ALTER TABLE STATEMENT_EQUIPMENT
ADD CONSTRAINT STATEMENT_EQUIPMENT_EQP#_FK 
FOREIGN KEY(EQP#)
REFERENCES EQUIPMENT(EQP#)
ON DELETE SET NULL;

ALTER TABLE STATEMENT_EQUIPMENT
DROP CONSTRAINT STATEMENT_EQUIPMENT_STM#_FK;

ALTER TABLE STATEMENT_EQUIPMENT
ADD CONSTRAINT STATEMENT_EQUIPMENT_STM#_FK
FOREIGN KEY(STM#)
REFERENCES STATEMENT(STM#)
ON DELETE SET NULL;

ALTER TABLE STATEMENT
DROP CONSTRAINT STATEMENT_SALES_PERSON#_FK;

ALTER TABLE STATEMENT
ADD CONSTRAINT STATEMENT_SALES_PERSON#_FK 
FOREIGN KEY(SALES_PERSON#)
REFERENCES SALESPERSON(SALES_PERSON#)
ON DELETE SET NULL;

ALTER TABLE STATEMENT
DROP CONSTRAINT STATMENT_CUST#_FK;

ALTER TABLE STATEMENT
ADD CONSTRAINT STATMENT_CUST#_FK 
FOREIGN KEY(CUST#)
REFERENCES CUSTOMER(CUST#)
ON DELETE SET NULL;
