CREATE TABLE STATEMENT(
    STM# VARCHAR2(9) NOT NULL,
    STATMENT_DATE CHAR (10) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
    SALES_PERSON# VARCHAR2 (20) NOT NULL,
    CUST# NUMBER(3) NOT NULL); 

CREATE TABLE STATEMENT_EQUIPMENT(
    STM# VARCHAR2(9) NOT NULL,
    EQP# VARCHAR2(9) NOT NULL,
    QTY NUMBER(4) NOT NULL,
    CHARGE NUMBER (6,2) NOT NULL);

CREATE TABLE EQUIP_TYPE(
    EQP_TYPE# CHAR(3) UNIQUE NOT NULL,
    EQP_TYPE_DESC CHAR(20) NOT NULL);

CREATE TABLE SALESPERSON (
    SALES_PERSON# VARCHAR2(20) UNIQUE NOT NULL,
    SALES_PERSON_NAME VARCHAR2(50) NOT NULL);

CREATE TABLE EQUIPMENT (
    EQP# VARCHAR2(30) UNIQUE NOT NULL,
    EQPDESC VARCHAR2(100) NOT NULL,
    EQP_TYPE# CHAR(3) NOT NULL);
    
CREATE TABLE CUSTOMER (
    CUST# NUMBER(3) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    ADDRESS VARCHAR2(100),
    PHONE VARCHAR2(12),
    FEDERAL_GST_LICENSENUMBER NUMBER(9) UNIQUE NOT NULL,
    CONSTRAINT CUST_GST_LICNUM_CHK
    CHECK (FEDERAL_GST_LICENSENUMBER >= 100000000 AND FEDERAL_GST_LICENSENUMBER < 999999999));

COMMIT;
