ALTER TABLE CUSTOMER
ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUST#);

ALTER TABLE EQUIP_TYPE
ADD CONSTRAINT EQUIP_TYPE_PK PRIMARY KEY (EQP_TYPE#);

ALTER TABLE STATEMENT
ADD CONSTRAINT STATEMENT_PK PRIMARY KEY(STM#);

ALTER TABLE EQUIPMENT
ADD CONSTRAINT EQUIPMENT_PK PRIMARY KEY(EQP#);

ALTER TABLE SALESPERSON
ADD CONSTRAINT SALESPERSON_PK PRIMARY KEY(SALES_PERSON#);

ALTER TABLE STATEMENT_EQUIPMENT
ADD CONSTRAINT STATEMENT_STM#_FK FOREIGN KEY (STM#)
    REFERENCES SALESPERSON(STM#)
ADD CONSTRAINT STATEMENT_EQP#_FK FOREIGN KEY (EQP#)
    REFERENCES CUSTOMER(EQP#);

ALTER TABLE EQUIPMENT
ADD CONSTRAINT EQUIPMENT_EQP_TYPE_FK FOREIGN KEY(EQP_TYPE#)
    REFERENCES EQUIP_TYPE(EQP_TYPE#);

ALTER TABLE STATEMENT
ADD CONSTRAINT SALESPERSON_SALES_PERSON#_FK FOREIGN KEY(SALES_PERSON#)
    REFERENCES STATEMENT (SALES_PERSON#);

ALTER TABLE STATEMENT_EQUIPMENT
ADD CONSTRAINT STATMENT_EQUIPMENT_STM#_FK FOREIGN KEY(STM#)
    REFERENCES STATEMENT (STM#)
ADD CONSTRAINT STATMENT_EQUIPMENT_EQP#_FK FOREIGN KEY(EQP#)
    REFERENCES EQUIPMENT (EQP#);

COMMIT;
