UPDATE SALESPERSON SET SALES_PERSON_NAME = 'Kenneth Co'
WHERE SALES_PERSON# = 17;

UPDATE SALESPERSON SET SALES_PERSON_NAME = 'Ahmed Bangura'
WHERE SALES_PERSON# = 20;

UPDATE CUSTOMER SET LAST_NAME = 'Farid'
WHERE CUST# = 771;

COMMIT;
