SELECT * FROM STATEMENT;
SELECT * FROM STATEMENT_EQUIPMENT;
SELECT * FROM EQUIP_TYPE;
SELECT * FROM CUSTOMER;
SELECT * FROM SALESPERSON;
SELECT * FROM EQUIPMENT;

DROP TABLE STATEMENT_EQUIPMENT;
DROP TABLE STATEMENT;
DROP TABLE CUSTOMER;
DROP TABLE SALESPERSON;
DROP TABLE EQUIPMENT;
DROP TABLE EQUIP_TYPE;
