CREATE VIEW SALESINFO AS
SELECT 
ET.EQP_TYPE#,
ET.EQP_TYPE_DESC,
E.EQP#,
E.EQPDESC,
ST.CHARGE,
ST.QTY,
S.STM#,
S.STATMENT_DATE,
S.SALES_PERSON#,
S.CUST#
FROM EQUIP_TYPE ET, EQUIPMENT E, STATEMENT_EQUIPMENT ST, STATEMENT S
WHERE ET.EQP_TYPE# = E.EQP_TYPE#
AND E.EQP# = ST.EQP#
AND ST.STM# = S.STM#;

CREATE VIEW SALESGT1000 AS
SELECT ET.EQP_TYPE#,
       ET.EQP_TYPE_DESC,
       E.EQP#,
       E.EQPDESC,
       ST.CHARGE,
       ST.QTY,
       S.STM#,
       S.STATMENT_DATE,
       S.SALES_PERSON#,
       S.CUST#
FROM EQUIP_TYPE ET, EQUIPMENT E, STATEMENT_EQUIPMENT ST, STATEMENT S
WHERE  ET.EQP_TYPE# = E.EQP_TYPE#
AND    E.EQP# = ST.EQP#
AND    ST.STM# = S.STM#
AND    ST.CHARGE >= 1000;

SELECT * FROM SALESGT1000;

----

